/* This file is autogenerated by Generator.ps1.
*  Any changes made to it may be lost the next time it is run.
*/


namespace LoxInterpreter.RazerLox
{
    public abstract class AExpression
    {

    }

    public sealed class Binary : AExpression
    {
        public readonly AExpression left;
        public readonly Token op;
        public readonly AExpression right;

        public Binary(AExpression left, Token op, AExpression right)
        {
            this.left = left;
            this.op = op;
            this.right = right;
        }
    }
    public sealed class Grouping : AExpression
    {
        public readonly AExpression expression;

        public Grouping(AExpression expression)
        {
            this.expression = expression;
        }
    }
    public sealed class Literal : AExpression
    {
        public readonly object value;

        public Literal(object value)
        {
            this.value = value;
        }
    }
    public sealed class Unary : AExpression
    {
        public readonly Token op;
        public readonly AExpression right;

        public Unary(Token op, AExpression right)
        {
            this.op = op;
            this.right = right;
        }
    }
}
