/* This file is autogenerated by Generator.ps1.
*  Any changes made to it may be lost the next time it is run.
*/


namespace LoxInterpreter.RazerLox
{
public abstract class AStatement
{
public interface IVisitor<T>
{
T VisitExpressionStatement(ExpressionStatement statement);

T VisitPrintStatement(PrintStatement statement);

}
public abstract T Accept<T>(IVisitor<T> visitor);
}
public sealed class ExpressionStatement : AStatement
{
public readonly AExpression expression;

public ExpressionStatement(AExpression expression)
{
this.expression = expression;
}

public override T Accept<T>(IVisitor<T> visitor)
{
return visitor.VisitExpressionStatement(this);
}
}
public sealed class PrintStatement : AStatement
{
public readonly AExpression expression;

public PrintStatement(AExpression expression)
{
this.expression = expression;
}

public override T Accept<T>(IVisitor<T> visitor)
{
return visitor.VisitPrintStatement(this);
}
}
}
